### ISSUE TITLE
Setzen von maxbytes über defaults.php bei der Installation wird nicht berücksichtigt.

### ISSUE THREAD

**Issue by andreasschenkel** [michaelpollak/moodle-assignsubmission_advanced#1]
![grafik](https://user-images.githubusercontent.com/31856043/130247444-e87124d8-4e24-4157-accc-61623f7dcaa9.png)

In der Datei local/defaults.php ist folgender Eintrag hinterlegt:
$defaults['assignsubmission_advanced']['maxbytes'] = 10485760;

Somit müsste die Einstellung in diesem Feld nach der Installation eigentlich nicht 256MB sondern 10MB sein.

**Comment by andreasschenkel** [comment]
![liste](https://user-images.githubusercontent.com/31856043/130251755-aa20406f-1740-40ee-a12a-282fad80fd9f.png)
In der DropDown-Liste kommt der Wert für 10MB nicht vor, daher konnte das vermutlich nicht funktionieren.

Im Live-System ist die Liste aber größer und da kommen auch 10MB vor. Dennoch wird dort bei der Installation der Default-Wert nicht eingestellt sondern der Maximal-Wert für das Moodle

**Comment by michaelpollak** [comment]
Ganz genau, die Werte in der defaults.php müssen in der Select Liste auswählbar sein :+1:  siehe auch https://docs.moodle.org/dev/Local_plugins

```
<?php
$defaults['assignsubmission_advanced']['maxwidth'] = 2048;
$defaults['assignsubmission_advanced']['maxfilesize'] = 5242880; // 5MB.
$defaults['assignsubmission_advanced']['maxbytes'] = 52428800; // 50MB.
```

Beim Testen muss das Plugin im Userinterface deinstalliert werden (/admin/plugins.php) um bereits gespeicherte Einstellungen zu löschen. Bei uns haben alle Tests erfolgreich geklappt, ich werd den Issue schliessen, falls dir doch noch etwas auffällt bitte wieder öffnen, danke Andreas!

TRANSLATION: Defaults set in local/defaults.php need to be available in the dropdown list (values) to take effect.
